services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: cd Fluxy && gunicorn Fluxy.wsgi:application --bind 0.0.0.0:$PORT
    regions:
      - oregon
