# Generated by Django 5.1.4 on 2025-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
