# Generated by Django 5.1.3 on 2024-11-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='title',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_time',
        ),
    ]
