# Generated by Django 5.1.4 on 2025-07-23 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_todotask_options_calendarevent_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_calendar_view', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('agenda', 'Agenda')], default='month', max_length=10)),
                ('week_starts_on', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday')], default='sunday', max_length=6)),
                ('dark_mode', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('emerald', 'Emerald'), ('ocean', 'Ocean'), ('sunset', 'Sunset'), ('royal', 'Royal'), ('monochrome', 'Monochrome')], default='classic', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
