# Generated by Django 5.1.4 on 2025-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_calendarevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
