# Generated by Django 5.1.3 on 2024-12-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_title_calendarevent_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event',
            field=models.CharField(max_length=255),
        ),
    ]
