# Generated by Django 5.1.4 on 2025-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todotask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='day_marking_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
