# Generated by Django 5.1.4 on 2025-08-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_llmusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
