# Generated by Django 5.1.4 on 2025-08-26 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notetab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['date', 'order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
