# Generated by Django 5.1.4 on 2025-09-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('emerald', 'Emerald'), ('ocean', 'Ocean'), ('coffee', 'Coffee'), ('royal', 'Royal'), ('monochrome', 'Monochrome')], default='classic', max_length=20),
        ),
        migrations.CreateModel(
            name='NoWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planner_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_work_days', to='myapp.plannerclass')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('planner_class', 'date')},
            },
        ),
    ]
