# Generated by Django 5.1.4 on 2025-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_usersettings_theme_noworkday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
