# Generated by Django 5.1.4 on 2025-10-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customuser_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_unlocked_features',
            field=models.BooleanField(default=False),
        ),
    ]
