# Generated by Django 5.1.4 on 2025-10-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_customuser_has_unlocked_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_unlocked_features',
            field=models.BooleanField(default=False),
        ),
    ]
