# Generated by Django 5.1.4 on 2025-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_customuser_has_unlocked_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['start_date', 'order', 'created_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
