# Generated by Django 5.1.4 on 2025-11-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_assignment_options_assignment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
