# Generated by Django 5.1.4 on 2025-12-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_customuser_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive marketing and re-engagement emails'),
        ),
    ]
