# Generated by Django 5.1.4 on 2026-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_customuser_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('completed', 'Completed'), ('uncompleted', 'Marked Not Completed'), ('deleted', 'Deleted'), ('purged_by_class_deletion', 'Purged by Class Deletion')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assignment_pk', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('class_pk', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_pk', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['changed_at'], name='myapp_assig_changed_b47acc_idx'), models.Index(fields=['assignment_pk', 'action'], name='myapp_assig_assignm_0b3aeb_idx')],
            },
        ),
    ]
