# Generated by Django 5.1.4 on 2026-09-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_assignmenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmenthistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Assignment history', 'verbose_name_plural': 'Assignment histories'},
        ),
        migrations.AlterModelOptions(
            name='plannerclass',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Planner class', 'verbose_name_plural': 'Planner classes'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User settings', 'verbose_name_plural': 'User settings'},
        ),
    ]
