# Generated by Django 5.1.4 on 2026-09-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_assignmenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='planner_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='myapp.plannerclass'),
        ),
    ]
